### ISSUE TITLE
Courier New does not render U+0301 correctly

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#103]
This affects `s9` in https://eel.is/c++draft/format.string.escaped#example-1:
![image](https://github.com/Eelis/cxxdraft-htmlgen/assets/10905931/9a7eefdd-d7ab-48e6-872c-18d3e9a95776)

The accent should be on the `e`, not the quote, like:

![image](https://github.com/Eelis/cxxdraft-htmlgen/assets/10905931/7d3bf5dd-ec68-46de-8dab-7f74b1e444ad)

**Comment by Eelis** [comment]
What browser are you using? It looks ok on my machine with both Chromium (111.0.5560.0) and Firefox (116.0.3):
![image](https://github.com/Eelis/cxxdraft-htmlgen/assets/22357/e8d08d94-a6d5-4620-9f56-dd3d0ab5eb6a)

**Comment by timsong-cpp** [comment]
Chrome 116.0.5845.111 on Windows 10. The whole line looks like

![image](https://github.com/Eelis/cxxdraft-htmlgen/assets/10905931/2f4b5358-b427-46b5-a8fe-a050ba9e5838)

This is clearly using a different font - your screenshot has a dot inside `0` and no serifs in `u`. Looking at [the sample on Wikipedia](https://en.wikipedia.org/wiki/File:Courier.svg) I don't think yours is actually using Courier New?

**Comment by Eelis** [comment]
Ah, I indeed didn't have Courier New installed, and so it used Liberation Mono instead.

I've now installed the MS Fonts, but the result still looks ok:
![image](https://github.com/Eelis/cxxdraft-htmlgen/assets/22357/12545df6-cbf8-4c13-9554-8662954a2b2c)

**Comment by timsong-cpp** [comment]
Different font version perhaps? This is what I see in Windows font settings with the text copied in, so it definitely looks font-related:

![image](https://github.com/Eelis/cxxdraft-htmlgen/assets/10905931/b0dd5658-7011-4a4f-b61a-f2667f98fee8)

**Comment by Eelis** [comment]
`font-manager` shows:

![image](https://github.com/Eelis/cxxdraft-htmlgen/assets/22357/698aac2f-f06f-4567-ae07-66377bcd48ec)

**Comment by Eelis** [comment]
Perhaps it would be useful to file a support ticket with Microsoft, to ask if there's anything they can do to make Courier New work well on their platform?

**Comment by timsong-cpp** [comment]
I see the same issue in both Chrome and Safari on my iPhone too, so it’s not just MS.

**Comment by Eelis** [comment]
I see, interesting. I just tried with Firefox and Chrome on my Android phone, and both rendered the character correctly.

**Comment by Eelis** [comment]
Purely speculative hypothesis: maybe the combining characters for accents are not in Courier New proper, but Linux cleverly uses the missing characters from another font, while Windows/Mac lack this sophistication?

**Comment by timsong-cpp** [comment]
It's definitely the font: copying the 6.92 font to WSL breaks rendering in Chrome-in-WSL, while the 2.82 font renders as desired in https://fontdrop.info/ in Chrome-on-Windows. Perhaps the 2.82 version is so old that it led to some sort of default or compatibility handling that ends up being better for this particular case?

Also, both versions misalign the `s2` example. It might be worthwhile to consider using a different font if the only version that semi-works is an ancient version not installed anywhere by default.

**Comment by Eelis** [comment]
Ah, thanks for the investigation. Good idea, I've changed to Roboto Mono now.

**Comment by jengelh** [comment]
Between the last comment and now, Roboto was switched out for Noto. Along that timeline, the problem with a misplaced dot reappeared. Today, it looks like so in Firefox/Linux:

![1](https://github.com/Eelis/cxxdraft-htmlgen/assets/8861948/b46b82ec-282f-47c6-9d72-c57ed74260b9)

Remember that 'ẹ́' is comprised of U+0065,U+0301,U+0323. In css2_002.css, we find that Noto is redefined from piecewise sub-files:

```
/* cyrillic */
@font-face {
  font-family: 'Noto Sans Mono';
 ...
  unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* vietnamese */
@font-face {
  font-family: 'Noto Sans Mono';
 ...
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1E
}
```

if I comment out the cyrillic block, the dot moves. My *hypothesis* is that the stitching done with `unicode-range` may cause the combination of a "latin"-source U+0065 with a "cyrillic"-sourced U+0301, and causing the page renderer to ignore all the kerning pairs in both "latin" and "cyrillic" sources involving U+0301 (because it's two separate fonts at this point!), thus misplacing the dot.

The remedy, I think, is to not use woff fragments anymore and replace it by downloading a single (large) font file that covers all scripts at once. This would be a somewhat significant change; https://eel.is/c++draft/format.string.escaped#example-1 currently downloads 34KB of font fragments, but NotoMono as a single entity would weigh in at ~207KB (when woff-ed).

(A PR is not deemed necessary currently, since [we're evaluating other font choices anyway](https://github.com/Eelis/cxxdraft-htmlgen/issues/98#issuecomment-1994814980).)
