### ISSUE TITLE
\pnum inside examples?

### ISSUE THREAD

**Issue by timsong-cpp** [Eelis/cxxdraft-htmlgen#27]
I'm having problems visiting eel.is right now, but [my copycat](https://timsong-cpp.github.io/cppwp/facets.examples#6) appears to have problems with a `\pnum` inside an example, producing stuff like

> locales.tex5110This example illustrates two architectural uses of class locale.

**Comment by Eelis** [comment]
Hmm, there was an upstream [effort](https://github.com/cplusplus/draft/issues/781) to get rid of \pnums in notes and examples, but the occurrences in [facets.examples] were not touched, and now remain as the only exceptions. :/  I'll give it some thought, thanks for the report.

**Comment by Eelis** [comment]
Since (to my knowledge) this is the only example containing \pnums, adding support for paragraphs nested in examples to cxxdraft-htmlgen doesn't seem worth the (considerable) effort, so on eel.is/c++draft I now instead use https://github.com/Eelis/draft/commit/9d0d0fad87f6ddcce75d7515fcefe22216f9dbf3 .

While this fixes the paragraphs numbers, it also makes the example non-selectable, but I can live with that.

**Comment by Eelis** [comment]
I've filed a [ticket](https://github.com/cplusplus/draft/issues/1852) to consider removing [facets.examples] altogether, which would solve the problem nicely.

**Comment by Eelis** [comment]
[facets.examples] has been removed.
