### ISSUE TITLE
Merge this repo into the C++ draft

### ISSUE THREAD

**Issue by oss-assist** [Eelis/cxxdraft-htmlgen#64]
Merge this repository with [github.com/cplusplus/draft](https://github.com/cplusplus/draft])

Very nice for this repo to be unified with the main C++ specification draft.
I'd have done this on myself, but I don't wanna develop it in parallel with this repo.
I can restructure and make a very nice PR that's integrated with the current build tools and directory structures exising in the C++ draft repo.

I'll do this anyway.

**Comment by Eelis** [comment]
Merging these repos would not make sense organizationally, since:
- I don't have (or need/want) commit rights in the draft repo, and
- the draft maintainers don't have (or need/want) commit rights in the cxxdraft-htmlgen repo. :)

Some other notes:

- If you're interested in reducing the distance between the official draft sources and the cxxdraft-htmlgen-generated draft at eel.is/c++draft, it might make more sense to try to upstream some of the couple dozen commits on [this branch](https://github.com/Eelis/draft/tree/cxxdraft-htmlgen-fixes), which is the one I actually use for eel.is/c++draft.

- Some people actually run (modified versions of) cxxdraft-htmlgen on other documents, such as TSs, which is a legitimate use case that I don't want to jeopardize by more closely coupling cxxdraft-htmlgen to the draft sources.

(P.S. What's the deal with using thumbs-up and heart-emoji "reactions" on your own feature request?)

**Comment by oss-assist** [comment]
@Eelis
> Merging these repos would not make sense organizationally, since:
> 
> * I don't have (or need/want) commit rights in the draft repo, and
> * the draft maintainers don't have (or need/want) commit rights in the cxxdraft-htmlgen repo. :)
> 
> Some other notes:
> 
> * If you're interested in reducing the distance between the official draft sources and the cxxdraft-htmlgen-generated draft at eel.is/c++draft, it might make more sense to try to upstream some of the couple dozen commits on [this branch](https://github.com/Eelis/draft/tree/cxxdraft-htmlgen-fixes), which is the one I actually use for eel.is/c++draft.
> * Some people actually run (modified versions of) cxxdraft-htmlgen on other documents, such as TSs, which is a legitimate use case that I don't want to jeopardize by more closely coupling cxxdraft-htmlgen to the draft sources.
> 

I'll make a pull request to merge this repo with the C++ draft anyway; so that it would be part of the official draft repo and made use of more broadly.
I won't need to make changes to the html generator codebase every half a second, so that wouldn't cause any issues.
You should have contibuted all the ideas behind [cxxdraft-htmlgen](https://github.com/Eelis/cxxdraft-htmlgen) to the official draft repo, further enriching the C++ draft.

> (P.S. What's the deal with using thumbs-up and heart-emoji "reactions" on your own feature request?)
Trick of the trade.
