### ISSUE TITLE
[iostream.cons] \iref{ostream} is covered with code

### ISSUE THREAD

**Issue by hewillk** [Eelis/cxxdraft-htmlgen#99]
<img width="789" alt="截圖 2023-02-10 下午3 03 02" src="https://user-images.githubusercontent.com/67143766/218024631-c4b98d8f-664e-4ce2-95ae-c2f4ce9617f6.png">

Should it be in the following format?

Effects: Initializes the base class subobjects with `basic_­istream<charT, traits>(sb)` ([[istream]](https://eel.is/c++draft/istream)) and `basic_­ostream<charT, traits>(sb)` ([[ostream]](https://eel.is/c++draft/ostream)).

**Comment by JohelEGP** [comment]
That's precisely how it is in the PDF.
![1676035705](https://user-images.githubusercontent.com/21071787/218103692-d3d13470-ae0f-4afc-a4ad-39a11536326d.png)

**Comment by Eelis** [comment]
Technically, replacement of spelled out section references with linkified terms/names is not done by cxxdraft-htmlgen, but by [this big patch](https://github.com/cplusplus/draft/commit/8b598149db83ab9be1e8e11048e1a16ddec15241) in my branch of the draft. Linkifying things (as opposed to spelling out a reference explicitly) is more conventional in webpages. It also reduces clutter, especially since cxxdraft-htmlgen uses section abbreviations instead of numbers for non-linkified references.

I do this linkification manually because I haven't written AI yet to figure out what preceding word or phrase a given reference is supposed to be for. And because I do it manually, it's ad-hoc and incomplete: there's loads of refs that could be linkified but that I haven't gotten around to linkifiying yet.

If you don't like linkfication of references, you can clone my branch of the draft, remove the aforementioned commit from it, and then run cxxdraft-htmlgen.
